global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "spring-backend"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets:
          - "order-service:8786"
          - "inventory-service:8381"
          - "payment-service:8180"
          - "product-service:8380"
