server:
  port: 4040  # Puerto del Gateway

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      cache:
        type: redis

    cache:
      redis:
        time-to-live: 600000  # 10 minutos (en milisegundos)

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
