server:
  port: 4040

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: my-client
            client-secret: Sht1KlSVMcXR48JuGHwDIGsjShNw4TyO
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:4040/login/oauth2/code/{registrationId}"
            scope: openid, messager.read
        provider:
          my-provider:
            issuer-uri: http://localhost:9090/auth/realms/my_realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost
    prefer-ip-address: true

