spring.application.name=payment-service
server.port=8280
spring.datasource.url=jdbc:postgresql://payment-postgres:5432/paymentdb
spring.datasource.username=user
spring.datasource.password=pwd3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect