server.port=8080
spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://order-postgres:5432/orderdb
spring.datasource.username=user
spring.datasource.password=pwd1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect