server:
  port: 8861

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 15000
    peer-node-read-timeout-ms: 5000
    peer-node-connect-timeout-ms: 2000
    peer-eureka-nodes-update-interval-ms: 15000
    response-cache-update-interval-ms: 5000
    response-cache-auto-expiration-in-seconds: 30

spring:
  application:
    name: eureka-server

