version: '3.8'

services:
  inventory-postgres:
    image: postgres:15
    container_name: inventory-postgres
    restart: always
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd2
    ports:
      - "5432:5432"
    networks:
      - spring-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  inventory-service:
    build: .
    container_name: inventory-service
    restart: always
    depends_on:
      - inventory-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-postgres:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd2
    ports:
      - "8080:8080"
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  pgdata:
